# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIAjustes.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ajustes(object):

    PASSWORD = "1234"
    passwordIngresado = ""    

    def setupUi(self, Ajustes):
        Ajustes.setObjectName("Ajustes")
        Ajustes.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ajustes.sizePolicy().hasHeightForWidth())
        Ajustes.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Ajustes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(250, -1, 250, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtPassword = QtWidgets.QLineEdit(Ajustes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPassword.sizePolicy().hasHeightForWidth())
        self.txtPassword.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtPassword.setFont(font)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.horizontalLayout_4.addWidget(self.txtPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(250, -1, 250, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.btn4 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 2, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.btnAsterisco = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnAsterisco.setFont(font)
        self.btnAsterisco.setObjectName("btnAsterisco")
        self.gridLayout.addWidget(self.btnAsterisco, 4, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.btnNumeral = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnNumeral.setFont(font)
        self.btnNumeral.setObjectName("btnNumeral")
        self.gridLayout.addWidget(self.btnNumeral, 4, 2, 1, 1)
        self.btn3 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 1, 2, 1, 1)
        self.btn0 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn0.setFont(font)
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 4, 1, 1, 1)
        self.btn5 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 2, 1, 1, 1)
        self.btnBorrar = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnBorrar.setFont(font)
        self.btnBorrar.setObjectName("btnBorrar")
        self.gridLayout.addWidget(self.btnBorrar, 0, 2, 1, 1)
        self.btn6 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 2, 2, 1, 1)
        self.btn7 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 3, 0, 1, 1)
        self.btn1 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 1, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn8.setFont(font)
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 3, 1, 1, 1)
        self.btn9 = QtWidgets.QPushButton(Ajustes)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn9.setFont(font)
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Ajustes)
        QtCore.QMetaObject.connectSlotsByName(Ajustes)

        self.btn0.clicked.connect(lambda:self.buttonClicked(self.btn0))
        self.btn1.clicked.connect(lambda:self.buttonClicked(self.btn1))
        self.btn2.clicked.connect(lambda:self.buttonClicked(self.btn2))
        self.btn3.clicked.connect(lambda:self.buttonClicked(self.btn3))
        self.btn4.clicked.connect(lambda:self.buttonClicked(self.btn4))
        self.btn5.clicked.connect(lambda:self.buttonClicked(self.btn5))
        self.btn6.clicked.connect(lambda:self.buttonClicked(self.btn6))
        self.btn7.clicked.connect(lambda:self.buttonClicked(self.btn7))
        self.btn8.clicked.connect(lambda:self.buttonClicked(self.btn8))
        self.btn9.clicked.connect(lambda:self.buttonClicked(self.btn9))
        self.btnAsterisco.clicked.connect(lambda:self.buttonClicked(self.btnAsterisco))
        self.btnNumeral.clicked.connect(lambda:self.buttonClicked(self.btnNumeral))
        self.btnBorrar.clicked.connect(self.btnBorrarClicked)

    def retranslateUi(self, Ajustes):
        _translate = QtCore.QCoreApplication.translate
        Ajustes.setWindowTitle(_translate("Ajustes", "Form"))
        self.btn4.setText(_translate("Ajustes", "4"))
        self.btn2.setText(_translate("Ajustes", "2"))
        self.pushButton.setText(_translate("Ajustes", "_"))
        self.btnAsterisco.setText(_translate("Ajustes", "*"))
        self.pushButton_4.setText(_translate("Ajustes", "_"))
        self.btnNumeral.setText(_translate("Ajustes", "#"))
        self.btn3.setText(_translate("Ajustes", "3"))
        self.btn0.setText(_translate("Ajustes", "0"))
        self.btn5.setText(_translate("Ajustes", "5"))
        self.btnBorrar.setText(_translate("Ajustes", "<-"))
        self.btn6.setText(_translate("Ajustes", "6"))
        self.btn7.setText(_translate("Ajustes", "7"))
        self.btn1.setText(_translate("Ajustes", "1"))
        self.btn8.setText(_translate("Ajustes", "8"))
        self.btn9.setText(_translate("Ajustes", "9"))

    def buttonClicked(self,btn):
        self.passwordIngresado += btn.text()
        self.txtPassword.setText(self.passwordIngresado)

    def btnBorrarClicked(self):
        self.passwordIngresado = self.passwordIngresado[0:len(self.passwordIngresado)-1]
        self.txtPassword.setText(self.passwordIngresado)	


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ajustes = QtWidgets.QWidget()
    ui = Ui_Ajustes()
    ui.setupUi(Ajustes)
    Ajustes.show()
    sys.exit(app.exec_())

