# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIMaxMinParametros.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MaxMinParametros(object):
    def setupUi(self, MaxMinParametros):
        MaxMinParametros.setObjectName("MaxMinParametros")
        MaxMinParametros.resize(800, 480)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MaxMinParametros)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(5, 50, 5, 50)
        self.gridLayout_2.setVerticalSpacing(50)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblFrecRespiratoria = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFrecRespiratoria.sizePolicy().hasHeightForWidth())
        self.lblFrecRespiratoria.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblFrecRespiratoria.setFont(font)
        self.lblFrecRespiratoria.setObjectName("lblFrecRespiratoria")
        self.gridLayout_2.addWidget(self.lblFrecRespiratoria, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinFrecRespMax = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinFrecRespMax.setFont(font)
        self.spinFrecRespMax.setObjectName("spinFrecRespMax")
        self.gridLayout.addWidget(self.spinFrecRespMax, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinFrecRespMin = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinFrecRespMin.setFont(font)
        self.spinFrecRespMin.setObjectName("spinFrecRespMin")
        self.gridLayout.addWidget(self.spinFrecRespMin, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(5, 50, 5, 50)
        self.gridLayout_4.setVerticalSpacing(50)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblVolumenTidal = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVolumenTidal.sizePolicy().hasHeightForWidth())
        self.lblVolumenTidal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblVolumenTidal.setFont(font)
        self.lblVolumenTidal.setObjectName("lblVolumenTidal")
        self.gridLayout_4.addWidget(self.lblVolumenTidal, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinVolTidalMax = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinVolTidalMax.setFont(font)
        self.spinVolTidalMax.setObjectName("spinVolTidalMax")
        self.gridLayout_3.addWidget(self.spinVolTidalMax, 1, 0, 1, 1)
        self.spinVolTidalMin = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinVolTidalMin.setFont(font)
        self.spinVolTidalMin.setObjectName("spinVolTidalMin")
        self.gridLayout_3.addWidget(self.spinVolTidalMin, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(5, 50, 5, 50)
        self.gridLayout_8.setVerticalSpacing(50)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lblRelacionIE = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRelacionIE.sizePolicy().hasHeightForWidth())
        self.lblRelacionIE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblRelacionIE.setFont(font)
        self.lblRelacionIE.setObjectName("lblRelacionIE")
        self.gridLayout_8.addWidget(self.lblRelacionIE, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinRelIEMax = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinRelIEMax.setFont(font)
        self.spinRelIEMax.setObjectName("spinRelIEMax")
        self.gridLayout_5.addWidget(self.spinRelIEMax, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.spinRelIEMin = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinRelIEMin.setFont(font)
        self.spinRelIEMin.setObjectName("spinRelIEMin")
        self.gridLayout_5.addWidget(self.spinRelIEMin, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(5, 50, 5, 50)
        self.gridLayout_10.setVerticalSpacing(50)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lblSensibilidad = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSensibilidad.sizePolicy().hasHeightForWidth())
        self.lblSensibilidad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblSensibilidad.setFont(font)
        self.lblSensibilidad.setObjectName("lblSensibilidad")
        self.gridLayout_10.addWidget(self.lblSensibilidad, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.spinSensMax = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinSensMax.setFont(font)
        self.spinSensMax.setObjectName("spinSensMax")
        self.gridLayout_6.addWidget(self.spinSensMax, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.spinSensMin = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinSensMin.setFont(font)
        self.spinSensMin.setObjectName("spinSensMin")
        self.gridLayout_6.addWidget(self.spinSensMin, 3, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(5, 50, 5, 50)
        self.gridLayout_12.setVerticalSpacing(50)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lblOxigeno = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOxigeno.sizePolicy().hasHeightForWidth())
        self.lblOxigeno.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblOxigeno.setFont(font)
        self.lblOxigeno.setObjectName("lblOxigeno")
        self.gridLayout_12.addWidget(self.lblOxigeno, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.spinOxiMax = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinOxiMax.setFont(font)
        self.spinOxiMax.setObjectName("spinOxiMax")
        self.gridLayout_7.addWidget(self.spinOxiMax, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(MaxMinParametros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 2, 0, 1, 1)
        self.spinOxiMin = QtWidgets.QSpinBox(MaxMinParametros)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spinOxiMin.setFont(font)
        self.spinOxiMin.setObjectName("spinOxiMin")
        self.gridLayout_7.addWidget(self.spinOxiMin, 3, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(MaxMinParametros)
        QtCore.QMetaObject.connectSlotsByName(MaxMinParametros)

        f = open("./max_min_data.txt","r") #abrir archivo para lectura y escritura
        lines = f.readlines()
        
        if len(lines)==10:
            self.spinFrecRespMax.setValue(int(lines[0]))
            self.spinFrecRespMin.setValue(int(lines[1]))
            self.spinVolTidalMax.setValue(int(lines[2]))
            self.spinVolTidalMin.setValue(int(lines[3]))
            self.spinRelIEMax.setValue(int(lines[4]))
            self.spinRelIEMin.setValue(int(lines[5]))
            self.spinSensMax.setValue(int(lines[6]))
            self.spinSensMin.setValue(int(lines[7]))
            self.spinOxiMax.setValue(int(lines[8]))
            self.spinOxiMin.setValue(int(lines[9]))
        f.close()


    def retranslateUi(self, MaxMinParametros):
        _translate = QtCore.QCoreApplication.translate
        MaxMinParametros.setWindowTitle(_translate("MaxMinParametros", "Form"))
        self.lblFrecRespiratoria.setText(_translate("MaxMinParametros", "Frec. Resp.:  "))
        self.label.setText(_translate("MaxMinParametros", "Máximo"))
        self.label_2.setText(_translate("MaxMinParametros", "Mínimo"))
        self.lblVolumenTidal.setText(_translate("MaxMinParametros", "Vol. Tidal:  "))
        self.label_3.setText(_translate("MaxMinParametros", "Máximo"))
        self.label_4.setText(_translate("MaxMinParametros", "Mínimo"))
        self.lblRelacionIE.setText(_translate("MaxMinParametros", "Rel. I/E:  "))
        self.label_5.setText(_translate("MaxMinParametros", "Máximo"))
        self.label_6.setText(_translate("MaxMinParametros", "Mínimo"))
        self.lblSensibilidad.setText(_translate("MaxMinParametros", "Sens.:   "))
        self.label_7.setText(_translate("MaxMinParametros", "Máximo"))
        self.label_8.setText(_translate("MaxMinParametros", "Mínimo"))
        self.lblOxigeno.setText(_translate("MaxMinParametros", "% Oxi.:   "))
        self.label_9.setText(_translate("MaxMinParametros", "Máximo"))
        self.label_10.setText(_translate("MaxMinParametros", "Mínimo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MaxMinParametros = QtWidgets.QWidget()
    ui = Ui_MaxMinParametros()
    ui.setupUi(MaxMinParametros)
    MaxMinParametros.show()
    sys.exit(app.exec_())

