# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIRespiracionControlada.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RespiracionControlada(object):
    def setupUi(self, RespiracionControlada):
        RespiracionControlada.setObjectName("RespiracionControlada")
        RespiracionControlada.resize(1078, 668)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(RespiracionControlada)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(25, 50, 25, 50)
        self.gridLayout_2.setVerticalSpacing(50)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblFrecRespiratoria = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFrecRespiratoria.sizePolicy().hasHeightForWidth())
        self.lblFrecRespiratoria.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblFrecRespiratoria.setFont(font)
        self.lblFrecRespiratoria.setObjectName("lblFrecRespiratoria")
        self.gridLayout_2.addWidget(self.lblFrecRespiratoria, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.sldFrecRespiratoria = QtWidgets.QSlider(RespiracionControlada)
        self.sldFrecRespiratoria.setOrientation(QtCore.Qt.Vertical)
        self.sldFrecRespiratoria.setObjectName("sldFrecRespiratoria")
        self.sldFrecRespiratoria.setMinimum(8)
        self.sldFrecRespiratoria.setMaximum(40)
        self.sldFrecRespiratoria.setValue(8)        
        self.sldFrecRespiratoria.setTickInterval(5)
        self.sldFrecRespiratoria.valueChanged.connect(self.sldFrecRespiratoriaValueChanged)
        
        self.gridLayout_3.addWidget(self.sldFrecRespiratoria, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(RespiracionControlada)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(25, 50, 25, 50)
        self.gridLayout_4.setVerticalSpacing(50)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblVolumenTidal = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVolumenTidal.sizePolicy().hasHeightForWidth())
        self.lblVolumenTidal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblVolumenTidal.setFont(font)
        self.lblVolumenTidal.setObjectName("lblVolumenTidal")
        self.gridLayout_4.addWidget(self.lblVolumenTidal, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")

        self.sldVolumenTidal = QtWidgets.QSlider(RespiracionControlada)
        self.sldVolumenTidal.setOrientation(QtCore.Qt.Vertical)
        self.sldVolumenTidal.setObjectName("sldVolumenTidal")
        self.sldVolumenTidal.setMinimum(200)
        self.sldVolumenTidal.setMaximum(800)
        self.sldVolumenTidal.setValue(200)        
        self.sldVolumenTidal.setTickInterval(5)
        self.sldVolumenTidal.valueChanged.connect(self.sldVolumenTidalValueChanged)
        self.gridLayout_7.addWidget(self.sldVolumenTidal, 1, 0, 1, 1)

        self.label_7 = QtWidgets.QLabel(RespiracionControlada)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(RespiracionControlada)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(25, 50, 25, 50)
        self.gridLayout_8.setVerticalSpacing(50)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lblRelacionIE = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRelacionIE.sizePolicy().hasHeightForWidth())
        self.lblRelacionIE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblRelacionIE.setFont(font)
        self.lblRelacionIE.setObjectName("lblRelacionIE")
        self.gridLayout_8.addWidget(self.lblRelacionIE, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_11 = QtWidgets.QLabel(RespiracionControlada)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 0, 1, 1, 1)
        
        self.sldRelacionIE = QtWidgets.QSlider(RespiracionControlada)
        self.sldRelacionIE.setOrientation(QtCore.Qt.Vertical)
        self.sldRelacionIE.setObjectName("sldRelacionIE")
        self.sldRelacionIE.setMinimum(1)
        self.sldRelacionIE.setMaximum(4)
        self.sldRelacionIE.setValue(1)        
        self.sldRelacionIE.setTickInterval(5)
        self.sldRelacionIE.valueChanged.connect(self.sldRelacionIEValueChanged)
        self.gridLayout_9.addWidget(self.sldRelacionIE, 1, 0, 1, 1)
        
        self.label_12 = QtWidgets.QLabel(RespiracionControlada)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 2, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(25, 50, 25, 50)
        self.gridLayout_10.setVerticalSpacing(50)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lblSensibilidad = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSensibilidad.sizePolicy().hasHeightForWidth())
        self.lblSensibilidad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblSensibilidad.setFont(font)
        self.lblSensibilidad.setObjectName("lblSensibilidad")
        self.gridLayout_10.addWidget(self.lblSensibilidad, 0, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_15 = QtWidgets.QLabel(RespiracionControlada)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 1, 1, 1, 1)
        
        self.sldSensibilidad = QtWidgets.QSlider(RespiracionControlada)
        self.sldSensibilidad.setOrientation(QtCore.Qt.Vertical)
        self.sldSensibilidad.setObjectName("sldSensibilidad")
        self.sldSensibilidad.setMinimum(1)
        self.sldSensibilidad.setMaximum(5)
        self.sldSensibilidad.setValue(1)        
        self.sldSensibilidad.setTickInterval(5)
        self.sldSensibilidad.valueChanged.connect(self.sldSensibilidadValueChanged)
        self.gridLayout_11.addWidget(self.sldSensibilidad, 1, 0, 1, 1)
        
        self.label_14 = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(RespiracionControlada)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 2, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(25, 50, 25, 50)
        self.gridLayout_12.setVerticalSpacing(50)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lblOxigeno = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOxigeno.sizePolicy().hasHeightForWidth())
        self.lblOxigeno.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblOxigeno.setFont(font)
        self.lblOxigeno.setObjectName("lblOxigeno")
        self.gridLayout_12.addWidget(self.lblOxigeno, 0, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_18 = QtWidgets.QLabel(RespiracionControlada)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_13.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(RespiracionControlada)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout_13.addWidget(self.label_19, 1, 1, 1, 1)
        
        self.sldOxigeno = QtWidgets.QSlider(RespiracionControlada)
        self.sldOxigeno.setOrientation(QtCore.Qt.Vertical)
        self.sldOxigeno.setObjectName("sldOxigeno")
        self.sldOxigeno.setMinimum(0)
        self.sldOxigeno.setMaximum(100)
        self.sldOxigeno.setValue(0)        
        self.sldOxigeno.setTickInterval(5)
        self.sldOxigeno.valueChanged.connect(self.sldOxigenoValueChanged)
        self.gridLayout_13.addWidget(self.sldOxigeno, 1, 0, 1, 1)
        
        self.label_20 = QtWidgets.QLabel(RespiracionControlada)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_13.addWidget(self.label_20, 2, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(RespiracionControlada)
        QtCore.QMetaObject.connectSlotsByName(RespiracionControlada)

    def retranslateUi(self, RespiracionControlada):
        _translate = QtCore.QCoreApplication.translate
        RespiracionControlada.setWindowTitle(_translate("RespiracionControlada", "Form"))
        self.lblFrecRespiratoria.setText(_translate("RespiracionControlada", "Frec. Respiratoria:   "))
        self.label_2.setText(_translate("RespiracionControlada", "8 vpm"))
        self.label_4.setText(_translate("RespiracionControlada", "40 vpm"))
        self.lblVolumenTidal.setText(_translate("RespiracionControlada", "Volumen Tidal:   "))
        self.label_6.setText(_translate("RespiracionControlada", "800 ml"))
        self.label_8.setText(_translate("RespiracionControlada", "200 ml"))
        self.lblRelacionIE.setText(_translate("RespiracionControlada", "Relación I/E:   "))
        self.label_10.setText(_translate("RespiracionControlada", "1:4"))
        self.label_12.setText(_translate("RespiracionControlada", "1:1"))
        self.lblSensibilidad.setText(_translate("RespiracionControlada", "Sensibilidad:   "))
        self.label_14.setText(_translate("RespiracionControlada", "5 cm"))
        self.label_16.setText(_translate("RespiracionControlada", "1 cm"))
        self.lblOxigeno.setText(_translate("RespiracionControlada", "% Oxigeno:   "))
        self.label_18.setText(_translate("RespiracionControlada", "100 %"))
        self.label_20.setText(_translate("RespiracionControlada", "0 %"))

    def sldFrecRespiratoriaValueChanged(self):
    	self.lblFrecRespiratoria.setText( "Frec. Respiratoria: " + str(self.sldFrecRespiratoria.value()) )

    def sldVolumenTidalValueChanged(self):
    	self.lblVolumenTidal.setText( "Volumen Tidal: " + str(self.sldVolumenTidal.value()) )

    def sldRelacionIEValueChanged(self):
    	self.lblRelacionIE.setText( "Relacion I/E: 1:" + str(self.sldRelacionIE.value()) )

    def sldSensibilidadValueChanged(self):
    	self.lblSensibilidad.setText( "Sensibilidad: " + str(self.sldSensibilidad.value()) )

    def sldOxigenoValueChanged(self):
    	self.lblOxigeno.setText( "Oxigeno: " + str(self.sldOxigeno.value()) ) 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RespiracionControlada = QtWidgets.QWidget()
    ui = Ui_RespiracionControlada()
    ui.setupUi(RespiracionControlada)
    RespiracionControlada.show()
    sys.exit(app.exec_())

